
# For tests with nektos/act use:
# act -e .\.github\workflows\fixtures\push.json -W .\.github\workflows\check-cogs.yml --container-options "-v /c/privat/gitssh/Red-DiscordBot/dist:/tmp/dist:ro" --secret-file .secrets

# To test with local Red-DiscordBot build artifact, mount the host folder containing the built wheels to /tmp/dist in the container.
# docker run -it --rm -v /c/privat/gitssh/Red-DiscordBot/dist:/tmp/dist python:3.11 bash
name: "Check Cogs"

on:
  push:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Red-DiscordBot
        uses: nntin/d-flows/actions/build-red-discordbot@feature/check-cog
        with:
          red_commit: ""                  # optional commit SHA
          artifact_name: "my-build-artifact"  # optional artifact name

  test-cogs:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Red-DiscordBot
        uses: nntin/d-flows/actions/install-red-discordbot@feature/check-cog
        with:
          artifact_name: "my-build-artifact"  # same artifact name used for build

      - name: Configure Red-DiscordBot
        uses: nntin/d-flows/actions/setup-red-discordbot@feature/check-cog
        with:
          token: ${{ secrets.DISCORD_BOT_TOKEN }}
          optional_args: "--no-cogs"  # Example optional argument to run without loading any cogs
        continue-on-error: true  # This step sets up the configuration, --dry-run fails due to bug in Red-DiscordBot
        
      - name: Test cogs via RPC
        uses: nntin/d-flows/actions/test-red-discordbot@feature/check-cog
        with:
          token: ${{ secrets.DISCORD_BOT_TOKEN }}
          cog_paths: "./dworld"
          rpc_port: "6133"
        # Validates that each listed cog can be loaded and unloaded through RPC without errors.
